### ISSUE TITLE
Feature Request: Support for xmr-node-proxy

### ISSUE THREAD

**Issue by caradex** [curumimxara/xmrig-monitor#1]
It would be nice if you can also support xmr-node-proxy. https://github.com/MoneroOcean/xmr-node-proxy

**Comment by bitlamas** [comment]
It already has support for XMR-Node-Proxy, you just need to use the `monitor-proxy.html` file. It doesn't support workers listing for the moment, but this is something that I plan to add in the future.

Remember that this is supposed to be a very simple monitor. Not a full-featured control center. :-)
