### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by snipeTR** [curumimxara/xmrig-monitor#4]
dont work xmrig proxy 2.6.2

**Comment by snipeTR** [comment]
![image](https://user-images.githubusercontent.com/31975916/40878379-e4125a8e-6698-11e8-936c-9ea0c9815e47.png)
![image](https://user-images.githubusercontent.com/31975916/40878390-10f3bbf6-6699-11e8-8861-2f89a58b094b.png)

**Comment by shigutso** [comment]
did you change the variables.js file? if yes, post it here

**Comment by snipeTR** [comment]
Yes

**Comment by bitlamas** [comment]
Can you please open the JavaScript console in your browser and see if there are any errors? If yes, please post it here.

**Comment by snipeTR** [comment]
thats ok its work. access token dont support shit.
